 EQPT Species List (SLIST) File:


           Number of elements =    14
           Number of basis species =    15

 data0.hmi.V8.R6
 CII: GEMBOCHS.V2-EQ8-data0.hmi.V8.R6
 THERMODYNAMIC DATABASE
 generated by GEMBOCHS.V2-Jewel.src.R5 02-dec-1996 11:27:50
 Output package:  eq3
 Data set:        hmi
 +--------------------------------------------------------------------


 element = O       , atwt =   15.99940
 element = Acetate , atwt =   59.04400
 element = Ca      , atwt =   40.07800
 element = Citrate , atwt =  189.10000
 element = Cl      , atwt =   35.45270
 element = Edtacid , atwt =  292.24500
 element = Fe      , atwt =   55.84700
 element = H       , atwt =    1.00794
 element = C       , atwt =   12.01100
 element = K       , atwt =   39.09830
 element = Mg      , atwt =   24.30500
 element = Na      , atwt =   22.98977
 element = Oxalate , atwt =   88.01960
 element = S       , atwt =   32.06600


 aqueous

     1  H2O                       Acetate-
     3  Ca++                      Citrate---
     5  Cl-                       EDTA----
     7  Fe++                      H+
     9  HCO3-                     K+
    11  Mg++                      Na+
    13  Oxalate--                 SO4--
    15  O2(g)                     Acetic_acid(aq)
    17  CO2(aq)                   CO3--
    19  CaAc+                     CaCit-
    21  CaCO3(aq)                 CaEDTA--
    23  CaOx(aq)                  H3Citrate(aq)
    25  H2Citrate-                HCitrate--
    27  H4EDTA(aq)                H3EDTA-
    29  H2EDTA--                  HEDTA---
    31  H2Oxalate(aq)             HOxalate-
    33  HSO4-                     MgAc+
    35  MgCit-                    MgCO3(aq)
    37  MgEDTA--                  MgOH+
    39  MgOx(aq)                  OH-


 minerals

     1  Anhydrite                 Antarcticite
     3  Aphthitalite              Aragonite
     5  Arcanite                  Bischofite
     7  MgSO4                     Bloedite
     9  Brucite                   Burkeite
    11  Ca2Cl2(OH)2:H2O           Ca4Cl2(OH)6:13H2O
    13  CaCl2:4H2O                CaCO3(am)
    15  CaCO3(am-cpa)             Calcite
    17  Carnallite                Chloromagnesite
    19  Dolomite                  Earlandite
    21  Epsomite                  Gaylussite
    23  Glauberite                Gypsum
    25  Halite                    Hexahydrite
    27  Hydromagne5424            Hydromagne4323
    29  Iron                      K2CO3:1.5H2O
    31  K3H(SO4)2                 K8H4(CO3)6:3H2O
    33  KNaCO3:6H2O               Kainite
    35  Kalicinite                Kieserite
    37  Leonite                   Lime
    39  Magnesite                 Mercallite
    41  Mirabilite                Misenite
    43  Na2CO3:7H2O               Na3H(SO4)2
    45  Na4Ca(SO4)3:2H2O          Nahcolite
    47  Natron                    Nesquehonite
    49  Oxychloride-Mg            Periclase
    51  Phase-5                   Picromerite
    53  Pirssonite                Polyhalite
    55  Portlandite               Sylvite
    57  Syngenite                 Tachyhydrite
    59  Thenardite                Thermonatrite
    61  Trona                     Trona-K
    63  Whewellite


 liquids

     0  none

 * Note - (EQPT/pcrsg) The pure liquids block has
       not been written on the DATA1 and DATA1F files,
       because the EQ3NR and EQ6 codes presently do not
       treat non-aqeuous liquids.


 gases

     1  CO2(g)                    H2(g)
     3  H2S(g)                    O2(g)


 solid solutions

     0  none
