 EQPT Species List (SLIST) File:


           Number of elements =    69
           Number of basis species =   140

 data0.sup.V8.R6
 CII: GEMBOCHS.V2-EQ8-data0.sup.V8.R6
 THERMODYNAMIC DATABASE
 generated by GEMBOCHS.V2-Jewel.src.R5 02-dec-1996 13:59:30
 Output package:  eq3
 Data set:        sup
 +--------------------------------------------------------------------


 element = O       , atwt =   15.99940
 element = Ag      , atwt =  107.86820
 element = Al      , atwt =   26.98154
 element = Ar      , atwt =   39.94800
 element = Au      , atwt =  196.96654
 element = B       , atwt =   10.81100
 element = Ba      , atwt =  137.32700
 element = Be      , atwt =    9.01218
 element = Br      , atwt =   79.90400
 element = Ca      , atwt =   40.07800
 element = Cd      , atwt =  112.41100
 element = Ce      , atwt =  140.11500
 element = Cl      , atwt =   35.45270
 element = Co      , atwt =   58.93320
 element = Cr      , atwt =   51.99610
 element = Cs      , atwt =  132.90543
 element = Cu      , atwt =   63.54600
 element = Dy      , atwt =  162.50000
 element = Er      , atwt =  167.26000
 element = Eu      , atwt =  151.96500
 element = F       , atwt =   18.99840
 element = Fe      , atwt =   55.84700
 element = Ga      , atwt =   69.72300
 element = Gd      , atwt =  157.25000
 element = H       , atwt =    1.00794
 element = As      , atwt =   74.92159
 element = C       , atwt =   12.01100
 element = P       , atwt =   30.97376
 element = He      , atwt =    4.00260
 element = Hg      , atwt =  200.59000
 element = Ho      , atwt =  164.93032
 element = I       , atwt =  126.90447
 element = In      , atwt =  114.82000
 element = K       , atwt =   39.09830
 element = Kr      , atwt =   83.80000
 element = La      , atwt =  138.90550
 element = Li      , atwt =    6.94100
 element = Lu      , atwt =  174.96700
 element = Mg      , atwt =   24.30500
 element = Mn      , atwt =   54.93805
 element = Mo      , atwt =   95.94000
 element = N       , atwt =   14.00674
 element = Na      , atwt =   22.98977
 element = Nd      , atwt =  144.24000
 element = Ne      , atwt =   20.17970
 element = Ni      , atwt =   58.69000
 element = Pb      , atwt =  207.20000
 element = Pd      , atwt =  106.42000
 element = Pr      , atwt =  140.90765
 element = Ra      , atwt =  226.02500
 element = Rb      , atwt =   85.46780
 element = Re      , atwt =  186.20700
 element = Rn      , atwt =  222.00000
 element = S       , atwt =   32.06600
 element = Sc      , atwt =   44.95591
 element = Se      , atwt =   78.96000
 element = Si      , atwt =   28.08550
 element = Sm      , atwt =  150.36000
 element = Sn      , atwt =  118.71000
 element = Sr      , atwt =   87.62000
 element = Tb      , atwt =  158.92534
 element = Tl      , atwt =  204.38330
 element = Tm      , atwt =  168.93421
 element = V       , atwt =   50.94150
 element = W       , atwt =  183.85000
 element = Xe      , atwt =  131.29000
 element = Y       , atwt =   88.90585
 element = Yb      , atwt =  173.04000
 element = Zn      , atwt =   65.39000


 aqueous

     1  H2O                       Ag+
     3  Al+++                     Ar(aq)
     5  Au+                       B(OH)3(aq)
     7  Ba++                      Be++
     9  Br-                       Ca++
    11  Cd++                      Ce+++
    13  Cl-                       Co++
    15  CrO4--                    Cs+
    17  Cu++                      Dy+++
    19  Er+++                     Eu+++
    21  F-                        Fe++
    23  Ga+++                     Gd+++
    25  H+                        H2AsO4-
    27  HCO3-                     HPO4--
    29  He(aq)                    Hg++
    31  Ho+++                     I-
    33  In+++                     K+
    35  Kr(aq)                    La+++
    37  Li+                       Lu+++
    39  Mg++                      Mn++
    41  MoO4--                    NH3(aq)
    43  Na+                       Nd+++
    45  Ne(aq)                    Ni++
    47  Pb++                      Pd++
    49  Pr+++                     Ra++
    51  Rb+                       ReO4-
    53  Rn(aq)                    SO4--
    55  Sc+++                     SeO3--
    57  SiO2(aq)                  Sm+++
    59  Sn++                      Sr++
    61  Tb+++                     Tl+
    63  Tm+++                     VO++
    65  WO4--                     Xe(aq)
    67  Y+++                      Yb+++
    69  Zn++                      O2(g)
    71  HS-                       Acetic_acid(aq)
    73  S2--                      S2O3--
    75  Glycine(aq)               Acetone(aq)
    77  Ag++                      Alanine(aq)
    79  Au+++                     Benzene(aq)
    81  Br3-                      BrO-
    83  BrO3-                     BrO4-
    85  Butanoic_acid(aq)         CN-
    87  CO(aq)                    ClO-
    89  ClO2-                     ClO3-
    91  ClO4-                     Co+++
    93  Cu+                       Ethanamine(aq)
    95  Ethane(aq)                Ethanol(aq)
    97  Ethylene(aq)              Ethyne(aq)
    99  Eu++                      Fe+++
   101  Formic_acid(aq)           Glycolic_acid(aq)
   103  H2(aq)                    H2AsO3-
   105  HSO5-                     HSe-
   107  Hg2++                     I3-
   109  IO-                       IO3-
   111  IO4-                      Lactic_acid(aq)
   113  Malonic_acid(aq)          Methane(aq)
   115  MnO4--                    N2(aq)
   117  NO2-                      NO3-
   119  O2(aq)                    Oxalic_acid(aq)
   121  Pentanoic_acid(aq)        Phenol(aq)
   123  Propanoic_acid(aq)        S2O4--
   125  S2O6--                    S2O8--
   127  S3--                      S3O6--
   129  S4--                      S4O6--
   131  S5--                      S5O6--
   133  SO3--                     SeO4--
   135  Sm++                      Succinic_acid(aq)
   137  Tl+++                     Toluene(aq)
   139  VO2+                      Yb++
   141  1-Butanamine(aq)          1-Butanol(aq)
   143  1-Butene(aq)              1-Butyne(aq)
   145  1-Heptanamine(aq)         1-Heptanol(aq)
   147  1-Heptene(aq)             1-Heptyne(aq)
   149  1-Hexanamine(aq)          1-Hexanol(aq)
   151  1-Hexene(aq)              1-Hexyne(aq)
   153  1-Octanamine(aq)          1-Octanol(aq)
   155  1-Octene(aq)              1-Octyne(aq)
   157  1-Pentanamine(aq)         1-Pentanol(aq)
   159  1-Pentene(aq)             1-Pentyne(aq)
   161  1-Propanamine(aq)         1-Propanol(aq)
   163  1-Propene(aq)             1-Propyne(aq)
   165  2-Butanone(aq)            2-Heptanone(aq)
   167  2-Hexanone(aq)            2-Hydroxybutanoate
   169  2-Hydroxybutanoic(aq)     2-Hydroxydecanoate
   171  2-Hydroxydecanoic(aq)     2-Hydroxyheptanoate
   173  2-Hydroxyheptanoic(aq)    2-Hydroxyhexanoate
   175  2-Hydroxyhexanoic(aq)     2-Hydroxynonanoate
   177  2-Hydroxynonanoic(aq)     2-Hydroxyoctanoate
   179  2-Hydroxyoctanoic(aq)     2-Hydroxypentanoate
   181  2-Hydroxypentanoic(aq)    2-Octanone(aq)
   183  2-Pentanone(aq)           Acetaldehyde(aq)
   185  Acetamide(aq)             Acetate
   187  Adipate                   Adipic_acid(aq)
   189  Ag(CH3COO)2-              Ag(CO3)2---
   191  AgCH3COO(aq)              AgCO3-
   193  AgCl(aq)                  AgCl2-
   195  AgCl3--                   AgCl4---
   197  AgNO3(aq)                 Al(CH3COO)2+
   199  Al(OH)2+                  AlCH3COO++
   201  AlO2-                     AlOH++
   203  Alanylglycine(aq)         Asparagine(aq)
   205  Aspartic_acid(aq)         Au(CH3COO)2-
   207  AuCH3COO(aq)              Azelaic_acid(aq)
   209  Azelate                   BF4-
   211  BO2-                      Ba(Ala)+
   213  Ba(Ala)2(aq)              Ba(But)+
   215  Ba(But)2(aq)              Ba(CH3COO)2(aq)
   217  Ba(For)+                  Ba(For)2(aq)
   219  Ba(Gly)+                  Ba(Gly)2(aq)
   221  Ba(Glyc)+                 Ba(Glyc)2(aq)
   223  Ba(Lac)+                  Ba(Lac)2(aq)
   225  Ba(Pent)+                 Ba(Pent)2(aq)
   227  Ba(Prop)+                 Ba(Prop)2(aq)
   229  BaCH3COO+                 BaCO3(aq)
   231  BaCl+                     BaF+
   233  Be(CH3COO)2(aq)           BeCH3COO+
   235  BeO2--                    Benzoate
   237  Benzoic_acid(aq)          Butanal(aq)
   239  Butanoate                 CO2(aq)
   241  CO3--                     Ca(Ala)+
   243  Ca(Ala)2(aq)              Ca(But)+
   245  Ca(But)2(aq)              Ca(CH3COO)2(aq)
   247  Ca(For)+                  Ca(For)2(aq)
   249  Ca(Gly)+                  Ca(Gly)2(aq)
   251  Ca(Glyc)+                 Ca(Glyc)2(aq)
   253  Ca(Lac)+                  Ca(Lac)2(aq)
   255  Ca(Pent)+                 Ca(Pent)2(aq)
   257  Ca(Prop)+                 Ca(Prop)2(aq)
   259  CaCH3COO+                 CaCO3(aq)
   261  CaCl+                     CaCl2(aq)
   263  CaF+                      CaHCO3+
   265  CaSO4(aq)                 Cd(Ala)+
   267  Cd(Ala)2(aq)              Cd(But)+
   269  Cd(But)2(aq)              Cd(CH3COO)2(aq)
   271  Cd(CH3COO)3-              Cd(For)+
   273  Cd(For)2(aq)              Cd(Gly)+
   275  Cd(Gly)2(aq)              Cd(Glyc)+
   277  Cd(Glyc)2(aq)             Cd(Lac)+
   279  Cd(Lac)2(aq)              Cd(Pent)+
   281  Cd(Pent)2(aq)             Cd(Prop)+
   283  Cd(Prop)2(aq)             CdCH3COO+
   285  Ce(CH3COO)2+              Ce(CH3COO)3(aq)
   287  CeBr++                    CeCH3COO++
   289  CeCO3+                    CeCl++
   291  CeCl2+                    CeCl3(aq)
   293  CeCl4-                    CeClO4++
   295  CeF++                     CeF2+
   297  CeF3(aq)                  CeF4-
   299  CeH2PO4++                 CeHCO3++
   301  CeIO3++                   CeNO3++
   303  CeO+                      CeO2-
   305  CeO2H(aq)                 CeOH++
   307  CeSO4+                    Co(Ala)+
   309  Co(Ala)2(aq)              Co(But)+
   311  Co(But)2(aq)              Co(CH3COO)2(aq)
   313  Co(CH3COO)3-              Co(For)+
   315  Co(For)2(aq)              Co(Gly)+
   317  Co(Gly)2(aq)              Co(Glyc)+
   319  Co(Glyc)2(aq)             Co(Lac)+
   321  Co(Lac)2(aq)              Co(Pent)+
   323  Co(Pent)2(aq)             Co(Prop)+
   325  Co(Prop)2(aq)             CoCH3COO+
   327  Cr2O7--                   Cs(CH3COO)2-
   329  CsBr(aq)                  CsCH3COO(aq)
   331  CsCl(aq)                  CsI(aq)
   333  Cu(Ala)+                  Cu(Ala)2(aq)
   335  Cu(But)+                  Cu(But)2(aq)
   337  Cu(CH3COO)2(aq)           Cu(CH3COO)2-
   339  Cu(CH3COO)3-              Cu(For)+
   341  Cu(For)2(aq)              Cu(Gly)+
   343  Cu(Gly)2(aq)              Cu(Glyc)+
   345  Cu(Glyc)2(aq)             Cu(Lac)+
   347  Cu(Lac)2(aq)              Cu(Pent)+
   349  Cu(Pent)2(aq)             Cu(Prop)+
   351  Cu(Prop)2(aq)             CuCH3COO(aq)
   353  CuCH3COO+                 Decanal(aq)
   355  Decanoate                 Decanoic_acid(aq)
   357  Diglycine(aq)             Diketopiperazine(aq)
   359  Dodecanoate               Dodecanoic_acid(aq)
   361  Dy(CH3COO)2+              Dy(CH3COO)3(aq)
   363  DyCH3COO++                DyCO3+
   365  DyCl++                    DyCl2+
   367  DyCl3(aq)                 DyCl4-
   369  DyF++                     DyF2+
   371  DyF3(aq)                  DyF4-
   373  DyH2PO4++                 DyHCO3++
   375  DyNO3++                   DyO+
   377  DyO2-                     DyO2H(aq)
   379  DyOH++                    DySO4+
   381  Er(CH3COO)2+              Er(CH3COO)3(aq)
   383  ErCH3COO++                ErCO3+
   385  ErCl++                    ErCl2+
   387  ErCl3(aq)                 ErCl4-
   389  ErF++                     ErF2+
   391  ErF3(aq)                  ErF4-
   393  ErH2PO4++                 ErHCO3++
   395  ErNO3++                   ErO+
   397  ErO2-                     ErO2H(aq)
   399  ErOH++                    ErSO4+
   401  Ethylacetate(aq)          Ethylbenzene(aq)
   403  Eu(Ala)+                  Eu(Ala)2(aq)
   405  Eu(But)+                  Eu(But)++
   407  Eu(But)2(aq)              Eu(But)2+
   409  Eu(CH3COO)2+              Eu(CH3COO)3(aq)
   411  Eu(For)+                  Eu(For)++
   413  Eu(For)2(aq)              Eu(For)2+
   415  Eu(Gly)+                  Eu(Gly)2(aq)
   417  Eu(Glyc)+                 Eu(Glyc)2(aq)
   419  Eu(Lac)+                  Eu(Lac)2(aq)
   421  Eu(Pent)+                 Eu(Pent)++
   423  Eu(Pent)2+                Eu(Prop)+
   425  Eu(Prop)++                Eu(Prop)2(aq)
   427  Eu(Prop)2+                EuCH3COO++
   429  EuCO3+                    EuCl+
   431  EuCl++                    EuCl2(aq)
   433  EuCl2+                    EuCl3(aq)
   435  EuCl3-                    EuCl4-
   437  EuCl4--                   EuF+
   439  EuF++                     EuF2(aq)
   441  EuF2+                     EuF3(aq)
   443  EuF3-                     EuF4-
   445  EuF4--                    EuH2PO4++
   447  EuHCO3++                  EuNO3++
   449  EuO+                      EuO2-
   451  EuO2H(aq)                 EuOH++
   453  EuSO4+                    Fe(Ala)+
   455  Fe(Ala)2(aq)              Fe(But)+
   457  Fe(But)2(aq)              Fe(CH3COO)2(aq)
   459  Fe(For)+                  Fe(For)2(aq)
   461  Fe(Gly)+                  Fe(Gly)2(aq)
   463  Fe(Glyc)+                 Fe(Glyc)2(aq)
   465  Fe(Lac)+                  Fe(Lac)2(aq)
   467  Fe(Pent)+                 Fe(Pent)2(aq)
   469  Fe(Prop)+                 Fe(Prop)2(aq)
   471  FeCH3COO+                 FeCl+
   473  FeCl2(aq)                 Formaldehyde(aq)
   475  Formate                   Gd(But)++
   477  Gd(But)2+                 Gd(CH3COO)2+
   479  Gd(CH3COO)3(aq)           Gd(For)++
   481  Gd(For)2+                 Gd(Pent)++
   483  Gd(Pent)2+                Gd(Prop)++
   485  Gd(Prop)2+                GdCH3COO++
   487  GdCO3+                    GdCl++
   489  GdCl2+                    GdCl3(aq)
   491  GdCl4-                    GdF++
   493  GdF2+                     GdF3(aq)
   495  GdF4-                     GdH2PO4++
   497  GdHCO3++                  GdNO3++
   499  GdO+                      GdO2-
   501  GdO2H(aq)                 GdOH++
   503  GdSO4+                    Glutamic_acid(aq)
   505  Glutamine(aq)             Glutarate
   507  Glutaric_acid(aq)         Glycolate
   509  H-Adipate                 H-Azelate
   511  H-Glutarate               H-Malonate
   513  H-Oxalate                 H-Pimelate
   515  H-Sebacate                H-Suberate
   517  H-Succinate               H2P2O7--
   519  H2PO4-                    H2S(aq)
   521  H2VO4-                    H3P2O7-
   523  H3PO4(aq)                 HAlO2(aq)
   525  HAsO4--                   HCN(aq)
   527  HCrO4-                    HF(aq)
   529  HF2-                      HNO3(aq)
   531  HO2-                      HSO3-
   533  HSO4-                     HSeO3-
   535  HSeO4-                    HSiO3-
   537  HVO4--                    Heptanal(aq)
   539  Heptanoate                Heptanoic_acid(aq)
   541  Hexanal(aq)               Hexanoate
   543  Hexanoic_acid(aq)         Hg(CH3COO)2(aq)
   545  Hg(CH3COO)3-              HgCH3COO+
   547  Ho(CH3COO)2+              Ho(CH3COO)3(aq)
   549  HoCH3COO++                HoCO3+
   551  HoCl++                    HoCl2+
   553  HoCl3(aq)                 HoCl4-
   555  HoF++                     HoF2+
   557  HoF3(aq)                  HoF4-
   559  HoH2PO4++                 HoHCO3++
   561  HoNO3++                   HoO+
   563  HoO2-                     HoO2H(aq)
   565  HoOH++                    HoSO4+
   567  Isoleucine(aq)            K(But)(aq)
   569  K(But)2-                  K(CH3COO)2-
   571  K(For)(aq)                K(For)2-
   573  K(Glyc)(aq)               K(Glyc)2-
   575  K(Lac)(aq)                K(Lac)2-
   577  K(Pent)(aq)               K(Pent)2-
   579  K(Prop)(aq)               K(Prop)2-
   581  KBr(aq)                   KCH3COO(aq)
   583  KCl(aq)                   KHSO4(aq)
   585  KI(aq)                    KSO4-
   587  La(But)++                 La(But)2+
   589  La(CH3COO)2+              La(CH3COO)3(aq)
   591  La(For)++                 La(For)2+
   593  La(Pent)++                La(Pent)2+
   595  La(Prop)++                La(Prop)2+
   597  LaCH3COO++                LaCO3+
   599  LaCl++                    LaCl2+
   601  LaCl3(aq)                 LaCl4-
   603  LaF++                     LaF2+
   605  LaF3(aq)                  LaF4-
   607  LaH2PO4++                 LaHCO3++
   609  LaNO3++                   LaO+
   611  LaO2-                     LaO2H(aq)
   613  LaOH++                    LaSO4+
   615  Lactate                   Leucine(aq)
   617  Leucylglycine(aq)         Li(CH3COO)2-
   619  LiCH3COO(aq)              LiCl(aq)
   621  Lu(CH3COO)2+              Lu(CH3COO)3(aq)
   623  LuCH3COO++                LuCO3+
   625  LuCl++                    LuCl2+
   627  LuCl3(aq)                 LuCl4-
   629  LuF++                     LuF2+
   631  LuF3(aq)                  LuF4-
   633  LuH2PO4++                 LuHCO3++
   635  LuNO3++                   LuO+
   637  LuO2-                     LuO2H(aq)
   639  LuOH++                    LuSO4+
   641  Malonate                  Methanamine(aq)
   643  Methanol(aq)              Methionine(aq)
   645  Mg(Ala)+                  Mg(Ala)2(aq)
   647  Mg(But)+                  Mg(But)2(aq)
   649  Mg(CH3COO)2(aq)           Mg(For)+
   651  Mg(For)2(aq)              Mg(Gly)+
   653  Mg(Gly)2(aq)              Mg(Glyc)+
   655  Mg(Glyc)2(aq)             Mg(Lac)+
   657  Mg(Lac)2(aq)              Mg(Pent)+
   659  Mg(Pent)2(aq)             Mg(Prop)+
   661  Mg(Prop)2(aq)             MgCH3COO+
   663  MgCO3(aq)                 MgCl+
   665  MgF+                      MgHCO3+
   667  Mn(Ala)+                  Mn(Ala)2(aq)
   669  Mn(But)+                  Mn(But)2(aq)
   671  Mn(CH3COO)2(aq)           Mn(CH3COO)3-
   673  Mn(For)+                  Mn(For)2(aq)
   675  Mn(Gly)+                  Mn(Gly)2(aq)
   677  Mn(Glyc)+                 Mn(Glyc)2(aq)
   679  Mn(Lac)+                  Mn(Lac)2(aq)
   681  Mn(Pent)+                 Mn(Pent)2(aq)
   683  Mn(Prop)+                 Mn(Prop)2(aq)
   685  MnCH3COO+                 MnCl+
   687  MnO4-                     MnSO4(aq)
   689  NH4(CH3COO)2-             NH4+
   691  NH4CH3COO(aq)             Na(But)(aq)
   693  Na(But)2-                 Na(CH3COO)2-
   695  Na(For)(aq)               Na(For)2-
   697  Na(Glyc)(aq)              Na(Glyc)2-
   699  Na(Lac)(aq)               Na(Lac)2-
   701  Na(Pent)(aq)              Na(Pent)2-
   703  Na(Prop)(aq)              Na(Prop)2-
   705  NaAlO2(aq)                NaBr(aq)
   707  NaCH3COO(aq)              NaCl(aq)
   709  NaF(aq)                   NaHSiO3(aq)
   711  NaI(aq)                   NaOH(aq)
   713  Nd(CH3COO)2+              Nd(CH3COO)3(aq)
   715  NdCH3COO++                NdCO3+
   717  NdCl++                    NdCl2+
   719  NdCl3(aq)                 NdCl4-
   721  NdF++                     NdF2+
   723  NdF3(aq)                  NdF4-
   725  NdH2PO4++                 NdHCO3++
   727  NdNO3++                   NdO+
   729  NdO2-                     NdO2H(aq)
   731  NdOH++                    NdSO4+
   733  Ni(Ala)+                  Ni(Ala)2(aq)
   735  Ni(But)+                  Ni(But)2(aq)
   737  Ni(CH3COO)2(aq)           Ni(CH3COO)3-
   739  Ni(For)+                  Ni(For)2(aq)
   741  Ni(Gly)+                  Ni(Gly)2(aq)
   743  Ni(Glyc)+                 Ni(Glyc)2(aq)
   745  Ni(Lac)+                  Ni(Lac)2(aq)
   747  Ni(Pent)+                 Ni(Pent)2(aq)
   749  Ni(Prop)+                 Ni(Prop)2(aq)
   751  NiCH3COO+                 NiCl+
   753  Nonanal(aq)               Nonanoate
   755  Nonanoic_acid(aq)         OH-
   757  Octanal(aq)               Octanoate
   759  Octanoic_acid(aq)         Oxalate
   761  PO4---                    Pb(Ala)+
   763  Pb(Ala)2(aq)              Pb(But)+
   765  Pb(But)2(aq)              Pb(CH3COO)2(aq)
   767  Pb(CH3COO)3-              Pb(For)+
   769  Pb(For)2(aq)              Pb(Gly)+
   771  Pb(Gly)2(aq)              Pb(Glyc)+
   773  Pb(Glyc)2(aq)             Pb(Lac)+
   775  Pb(Lac)2(aq)              Pb(Pent)+
   777  Pb(Pent)2(aq)             Pb(Prop)+
   779  Pb(Prop)2(aq)             PbCH3COO+
   781  PbCl+                     PbCl2(aq)
   783  PbCl3-                    PbCl4--
   785  PdCl+                     PdCl2(aq)
   787  PdCl3-                    PdCl4--
   789  PdO(aq)                   PdOH+
   791  Pentanal(aq)              Pentanoate
   793  Phenylalanine(aq)         Pimelate
   795  Pimelic_acid(aq)          Pr(CH3COO)2+
   797  Pr(CH3COO)3(aq)           PrCH3COO++
   799  PrCO3+                    PrCl++
   801  PrCl2+                    PrCl3(aq)
   803  PrCl4-                    PrF++
   805  PrF2+                     PrF3(aq)
   807  PrF4-                     PrH2PO4++
   809  PrHCO3++                  PrNO3++
   811  PrO+                      PrO2-
   813  PrO2H(aq)                 PrOH++
   815  PrSO4+                    Propanal(aq)
   817  Propane(aq)               Propanoate
   819  Ra(CH3COO)2(aq)           RaCH3COO+
   821  Rb(CH3COO)2-              RbBr(aq)
   823  RbCH3COO(aq)              RbCl(aq)
   825  RbF(aq)                   RbI(aq)
   827  S2O5--                    SO2(aq)
   829  Sc(CH3COO)2+              Sc(CH3COO)3(aq)
   831  ScCH3COO++                Sebacate
   833  Sebacic_acid(aq)          Serine(aq)
   835  SiF6--                    Sm(CH3COO)2+
   837  Sm(CH3COO)3(aq)           SmCH3COO++
   839  SmCO3+                    SmCl++
   841  SmCl2+                    SmCl3(aq)
   843  SmCl4-                    SmF++
   845  SmF2+                     SmF3(aq)
   847  SmF4-                     SmH2PO4++
   849  SmHCO3++                  SmNO3++
   851  SmO+                      SmO2-
   853  SmO2H(aq)                 SmOH++
   855  SmSO4+                    Sr(Ala)+
   857  Sr(Ala)2(aq)              Sr(But)+
   859  Sr(But)2(aq)              Sr(CH3COO)2(aq)
   861  Sr(For)+                  Sr(For)2(aq)
   863  Sr(Gly)+                  Sr(Gly)2(aq)
   865  Sr(Glyc)+                 Sr(Glyc)2(aq)
   867  Sr(Lac)+                  Sr(Lac)2(aq)
   869  Sr(Pent)+                 Sr(Pent)2(aq)
   871  Sr(Prop)+                 Sr(Prop)2(aq)
   873  SrCH3COO+                 SrCO3(aq)
   875  SrCl+                     SrF+
   877  Suberate                  Suberic_acid(aq)
   879  Succinate                 Tb(CH3COO)2+
   881  Tb(CH3COO)3(aq)           TbCH3COO++
   883  TbCO3+                    TbCl++
   885  TbCl2+                    TbCl3(aq)
   887  TbCl4-                    TbF++
   889  TbF2+                     TbF3(aq)
   891  TbF4-                     TbH2PO4++
   893  TbHCO3++                  TbNO3++
   895  TbO+                      TbO2-
   897  TbO2H(aq)                 TbOH++
   899  TbSO4+                    Threonine(aq)
   901  Tl(CH3COO)2-              TlCH3COO(aq)
   903  Tm(CH3COO)2+              Tm(CH3COO)3(aq)
   905  TmCH3COO++                TmCO3+
   907  TmCl++                    TmCl2+
   909  TmCl3(aq)                 TmCl4-
   911  TmF++                     TmF2+
   913  TmF3(aq)                  TmF4-
   915  TmH2PO4++                 TmHCO3++
   917  TmNO3++                   TmO+
   919  TmO2-                     TmO2H(aq)
   921  TmOH++                    TmSO4+
   923  Tryptophan(aq)            Tyrosine(aq)
   925  Undecanoate               Undecanoic_acid(aq)
   927  Urea(aq)                  Valine(aq)
   929  Y(CH3COO)2+               Y(CH3COO)3(aq)
   931  YCH3COO++                 Yb(But)++
   933  Yb(But)2+                 Yb(CH3COO)2+
   935  Yb(CH3COO)3(aq)           Yb(For)++
   937  Yb(For)2+                 Yb(Pent)++
   939  Yb(Pent)2+                Yb(Prop)++
   941  Yb(Prop)2+                YbCH3COO++
   943  YbCO3+                    YbCl++
   945  YbCl2+                    YbCl3(aq)
   947  YbCl4-                    YbF++
   949  YbF2+                     YbF3(aq)
   951  YbF4-                     YbH2PO4++
   953  YbHCO3++                  YbNO3++
   955  YbO+                      YbO2-
   957  YbO2H(aq)                 YbOH++
   959  YbSO4+                    Zn(Ala)+
   961  Zn(Ala)2(aq)              Zn(But)+
   963  Zn(But)2(aq)              Zn(CH3COO)2(aq)
   965  Zn(CH3COO)3-              Zn(For)+
   967  Zn(For)2(aq)              Zn(Gly)+
   969  Zn(Gly)2(aq)              Zn(Glyc)+
   971  Zn(Glyc)2(aq)             Zn(Lac)+
   973  Zn(Lac)2(aq)              Zn(Pent)+
   975  Zn(Pent)2(aq)             Zn(Prop)+
   977  Zn(Prop)2(aq)             ZnCH3COO+
   979  ZnCl+                     ZnCl2(aq)
   981  ZnCl3-                    ZnCl4--
   983  a-Aminobutyric_acid(aq)   m-Toluate
   985  m-Toluic_acid(aq)         n-Butane(aq)
   987  n-Butylbenzene(aq)        n-Heptane(aq)
   989  n-Heptylbenzene(aq)       n-Hexane(aq)
   991  n-Hexylbenzene(aq)        n-Octane(aq)
   993  n-Octylbenzene(aq)        n-Pentane(aq)
   995  n-Pentylbenzene(aq)       n-Propylbenzene(aq)
   997  o-Toluate                 o-Toluic_acid(aq)
   999  p-Toluate                 p-Toluic_acid(aq)


 minerals

     1  Acanthite                 Silver
     3  Akermanite                Alabandite
     5  Albite                    Albite_high
     7  Albite_low                Alunite
     9  Analcime-s92              Analcime-dehy-s92
    11  Andalusite                Andradite
    13  Anglesite                 Anhydrite
    15  Annite                    Anorthite
    17  Anthophyllite             Antigorite
    19  Aragonite                 Artinite
    21  Gold                      Azurite
    23  Barite                    Berndtite
    25  Boehmite                  Bornite
    27  Brucite                   Bunsenite
    29  Graphite                  Ca-Al_Pyroxene
    31  Calcite                   Cassiterite
    33  Celestite                 Cerussite
    35  Chalcedony                Chalcocite
    37  Chalcopyrite              Chlorargyrite
    39  Chrysotile                Cinnabar
    41  Clinochlore-14A           Clinochlore-7A
    43  Clinozoisite              Coesite
    45  Cordierite_anhyd          Cordierite_hydr
    47  Corundum                  Covellite
    49  Cristobalite(alpha)       Cristobalite(beta)
    51  Copper                    Cuprite
    53  Diaspore                  Diopside
    55  Dolomite                  Dolomite-dis
    57  Dolomite-ord              Enstatite
    59  Epidote                   Epidote-ord
    61  Fayalite                  Iron
    63  FeO                       Ferrosilite
    65  Fluorite                  Forsterite
    67  Galena                    Gehlenite
    69  Gibbsite                  Grossular
    71  Halite                    Hedenbergite
    73  Hematite                  Herzenbergite
    75  Huntite                   Hydromagnesite
    77  Jadeite                   K-Feldspar
    79  K2O                       Kalsilite
    81  Kaolinite                 Kyanite
    83  Laumontite                Lawsonite
    85  Lime                      Magnesite
    87  Magnetite                 Malachite
    89  Manganosite               Margarite
    91  Maximum_Microcline        Merwinite
    93  Metacinnabar              Monticellite
    95  Muscovite                 Na2O
    97  Nepheline                 Nesquehonite
    99  Nickel                    Paragonite
   101  Pargasite                 Palladium
   103  PdO                       Periclase
   105  Phlogopite                Prehnite
   107  Pyrite                    Pyrophyllite
   109  Pyrrhotite                Quartz
   111  Rhodochrosite             Romarchite
   113  Sanidine_high             Sepiolite
   115  SiO2(am)                  Siderite
   117  Sillimanite               Smithsonite
   119  Tin                       Sphalerite
   121  Spinel                    Strontianite
   123  Sylvite                   Talc
   125  Tenorite                  Tremolite
   127  Wairakite                 Witherite
   129  Wollastonite              Wurtzite
   131  Zoisite


 liquids

     1  Quicksilver

 * Note - (EQPT/pcrsg) The pure liquids block has
       not been written on the DATA1 and DATA1F files,
       because the EQ3NR and EQ6 codes presently do not
       treat non-aqeuous liquids.


 gases

     1  Argon                     C2H4(g)
     3  CH4(g)                    CO(g)
     5  CO2(g)                    H2(g)
     7  H2O(g)                    H2S(g)
     9  Helium                    Krypton
    11  Nitrogen                  NH3(g)
    13  Neon                      O2(g)
    15  Radon                     S2(g)
    17  SO2(g)                    Xenon


 solid solutions

     0  none
