 EQPT Species List (SLIST) File:


           Number of elements =     9
           Number of basis species =    10

 data0.hmw.V8.R6
 CII: GEMBOCHS.V2-EQ8-data0.hmw.V8.R6
 THERMODYNAMIC DATABASE
 generated by GEMBOCHS.V2-Jewel.src.R5 02-dec-1996 11:27:50
 Output package:  eq3
 Data set:        hmw
 +--------------------------------------------------------------------


 element = O       , atwt =   15.99940
 element = Ca      , atwt =   40.07800
 element = Cl      , atwt =   35.45270
 element = H       , atwt =    1.00794
 element = C       , atwt =   12.01100
 element = K       , atwt =   39.09830
 element = Mg      , atwt =   24.30500
 element = Na      , atwt =   22.98977
 element = S       , atwt =   32.06600


 aqueous

     1  H2O                       Ca++
     3  Cl-                       H+
     5  HCO3-                     K+
     7  Mg++                      Na+
     9  SO4--                     O2(g)
    11  CO2(aq)                   CO3--
    13  CaCO3(aq)                 HSO4-
    15  MgCO3(aq)                 MgOH+
    17  OH-


 minerals

     1  Anhydrite                 Antarcticite
     3  Aphthitalite              Aragonite
     5  Arcanite                  Bischofite
     7  Bloedite                  Brucite
     9  Burkeite                  Ca2Cl2(OH)2:H2O
    11  Ca4Cl2(OH)6:13H2O         CaCl2:4H2O
    13  Calcite                   Carnallite
    15  Dolomite                  Epsomite
    17  Gaylussite                Glauberite
    19  Gypsum                    Halite
    21  Hexahydrite               K2CO3:1.5H2O
    23  K3H(SO4)2                 K8H4(CO3)6:3H2O
    25  KNaCO3:6H2O               Kainite
    27  Kalicinite                Kieserite
    29  Leonite                   Magnesite
    31  Mercallite                Mirabilite
    33  Misenite                  Na2CO3:7H2O
    35  Na3H(SO4)2                Na4Ca(SO4)3:2H2O
    37  Nahcolite                 Natron
    39  Nesquehonite              Oxychloride-Mg
    41  Picromerite               Pirssonite
    43  Polyhalite                Portlandite
    45  Sylvite                   Syngenite
    47  Tachyhydrite              Thenardite
    49  Thermonatrite             Trona
    51  Trona-K


 liquids

     0  none

 * Note - (EQPT/pcrsg) The pure liquids block has
       not been written on the DATA1 and DATA1F files,
       because the EQ3NR and EQ6 codes presently do not
       treat non-aqeuous liquids.


 gases

     1  CO2(g)                    H2(g)
     3  O2(g)


 solid solutions

     0  none
